service: push-notification-lambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 512 # 512MB
  timeout: 30 # 30s
functions:
  main:
    handler: index.handler
    events: 
      - http: 
          path: / 
          method: POST
          cors: true